import {
  User,
  PatientProfile,
  FamilyMember,
  Hospital,
  Department,
  Doctor,
  AppointmentSlot,
  Appointment,
  QueueState,
  PaymentRecord,
  Prescription,
  PharmacyOrder,
  LabTestCatalog,
  LabOrder,
  TimelineEvent,
  InsuranceClaim,
  TelemedicineSession,
  AppNotification,
  AuditLogEntry,
} from './ayulink';

export interface DatabaseState {
  users: User[];
  patientProfiles: PatientProfile[];
  familyMembers: FamilyMember[];
  hospitals: Hospital[];
  departments: Department[];
  doctors: Doctor[];
  slots: AppointmentSlot[];
  appointments: Appointment[];
  queues: QueueState[];
  payments: PaymentRecord[];
  prescriptions: Prescription[];
  pharmacyOrders: PharmacyOrder[];
  labCatalog: LabTestCatalog[];
  labOrders: LabOrder[];
  timeline: TimelineEvent[];
  insuranceClaims: InsuranceClaim[];
  telemedicineSessions: TelemedicineSession[];
  notifications: AppNotification[];
  auditLogs: AuditLogEntry[];
  tokenCounter: number;
}

export function createInitialSeedState(): DatabaseState {
  const users: User[] = [
    {
      id: 'usr-patient-mison',
      name: 'Mison Khatiwada',
      email: 'mison@ayulink.np',
      phone: '+977-9841009200',
      role: 'patient',
      patientId: 'pat-mison',
      verified: true,
      createdAt: '2026-01-15T08:00:00Z',
    },
    {
      id: 'usr-doc-suman',
      name: 'Dr. Suman Sharma',
      email: 'suman.sharma@cityhospital.np',
      phone: '+977-9851100201',
      role: 'doctor',
      hospitalId: 'hosp-city',
      doctorId: 'doc-suman',
      verified: true,
      createdAt: '2025-11-10T08:00:00Z',
    },
    {
      id: 'usr-doc-anita',
      name: 'Dr. Anita Karki',
      email: 'anita.karki@cityhospital.np',
      phone: '+977-9851100202',
      role: 'doctor',
      hospitalId: 'hosp-city',
      doctorId: 'doc-anita',
      verified: true,
      createdAt: '2025-11-12T08:00:00Z',
    },
    {
      id: 'usr-doc-raj',
      name: 'Dr. Raj Thapa',
      email: 'raj.thapa@cityhospital.np',
      phone: '+977-9851100203',
      role: 'doctor',
      hospitalId: 'hosp-city',
      doctorId: 'doc-raj',
      verified: true,
      createdAt: '2025-12-01T08:00:00Z',
    },
    {
      id: 'usr-hosp-admin',
      name: 'Prakash Adhikari',
      email: 'admin@cityhospital.np',
      phone: '+977-56-524100',
      role: 'hospital_admin',
      hospitalId: 'hosp-city',
      verified: true,
      createdAt: '2025-10-01T08:00:00Z',
    },
    {
      id: 'usr-receptionist',
      name: 'Binita Gurung',
      email: 'frontdesk@cityhospital.np',
      phone: '+977-56-524101',
      role: 'receptionist',
      hospitalId: 'hosp-city',
      verified: true,
      createdAt: '2025-10-05T08:00:00Z',
    },
    {
      id: 'usr-nurse',
      name: 'Sunita Tamang',
      email: 'triage@cityhospital.np',
      phone: '+977-56-524105',
      role: 'nurse',
      hospitalId: 'hosp-city',
      verified: true,
      createdAt: '2025-10-06T08:00:00Z',
    },
    {
      id: 'usr-lab',
      name: 'Dipesh Shrestha',
      email: 'pathology@cityhospital.np',
      phone: '+977-56-524102',
      role: 'lab_staff',
      hospitalId: 'hosp-city',
      verified: true,
      createdAt: '2025-10-08T08:00:00Z',
    },
    {
      id: 'usr-pharmacy',
      name: 'Kabita Poudel',
      email: 'dispensary@cityhospital.np',
      phone: '+977-56-524103',
      role: 'pharmacist',
      hospitalId: 'hosp-city',
      verified: true,
      createdAt: '2025-10-10T08:00:00Z',
    },
    {
      id: 'usr-insurance',
      name: 'Nabin Subedi',
      email: 'claims@cityhospital.np',
      phone: '+977-56-524104',
      role: 'insurance_staff',
      hospitalId: 'hosp-city',
      verified: true,
      createdAt: '2025-10-12T08:00:00Z',
    },
    {
      id: 'usr-super-admin',
      name: 'AyuLink National Governance',
      email: 'governance@ayulink.gov.np',
      phone: '+977-1-4200900',
      role: 'super_admin',
      verified: true,
      createdAt: '2025-09-01T08:00:00Z',
    },
  ];

  const patientProfiles: PatientProfile[] = [
    {
      id: 'pat-mison',
      userId: 'usr-patient-mison',
      name: 'Mison Khatiwada',
      age: 26,
      gender: 'Male',
      bloodGroup: 'O+',
      phone: '+977-9841009200',
      email: 'mison@ayulink.np',
      address: 'Hospital Road-10, Bharatpur, Chitwan',
      allergies: ['Penicillin', 'Sulfonamides'],
      criticalConditions: ['Mild Essential Hypertension (Controlled)', 'Seasonal Allergic Rhinitis'],
      emergencyContact: {
        name: 'Ramesh Khatiwada',
        relation: 'Father',
        phone: '+977-9841234567',
      },
      importantMedicines: ['Amlodipine 5mg (Once Daily)', 'Cetirizine 10mg (PRN)'],
      healthIdCode: 'AL-NP-8F29K4',
      qrSecurityToken: 'AL-SEC-TOKEN-8F29K4-9921A',
      insurancePolicyNumber: 'HIB-NP-2026-88412',
    },
    {
      id: 'pat-ram',
      userId: 'usr-pat-ram',
      name: 'Ram Thapa',
      age: 54,
      gender: 'Male',
      bloodGroup: 'B+',
      phone: '+977-9845011223',
      email: 'ram.thapa@demo.np',
      address: 'Ratnanagar-2, Tandi, Chitwan',
      allergies: ['None Known'],
      criticalConditions: ['Type 2 Diabetes Mellitus', 'Post-Angioplasty (2024)'],
      emergencyContact: {
        name: 'Gita Thapa',
        relation: 'Spouse',
        phone: '+977-9845011224',
      },
      importantMedicines: ['Metformin 500mg BD', 'Aspirin 75mg OD', 'Atorvastatin 20mg HS'],
      healthIdCode: 'AL-NP-3C91M2',
      qrSecurityToken: 'AL-SEC-TOKEN-3C91M2-7741B',
      insurancePolicyNumber: 'HIB-NP-2026-44109',
    },
    {
      id: 'pat-sita',
      userId: 'usr-pat-sita',
      name: 'Sita Karki',
      age: 38,
      gender: 'Female',
      bloodGroup: 'A+',
      phone: '+977-9845099881',
      email: 'sita.karki@demo.np',
      address: 'Gaindakot-4, Nawalpur',
      allergies: ['Ibuprofen (NSAIDs)'],
      criticalConditions: ['Hypothyroidism'],
      emergencyContact: {
        name: 'Bikash Karki',
        relation: 'Spouse',
        phone: '+977-9845099882',
      },
      importantMedicines: ['Levothyroxine 50mcg OD'],
      healthIdCode: 'AL-NP-5D44P8',
      qrSecurityToken: 'AL-SEC-TOKEN-5D44P8-6612C',
    },
    {
      id: 'pat-hari',
      userId: 'usr-pat-hari',
      name: 'Hari Gurung',
      age: 45,
      gender: 'Male',
      bloodGroup: 'AB+',
      phone: '+977-9855022334',
      email: 'hari.gurung@demo.np',
      address: 'Narayangarh-3, Pulchowk, Chitwan',
      allergies: ['Amoxicillin'],
      criticalConditions: ['Chronic Sinusitis'],
      emergencyContact: {
        name: 'Purna Gurung',
        relation: 'Brother',
        phone: '+977-9855022335',
      },
      importantMedicines: ['Fluticasone Nasal Spray'],
      healthIdCode: 'AL-NP-7K19T5',
      qrSecurityToken: 'AL-SEC-TOKEN-7K19T5-1109D',
    },
  ];

  const familyMembers: FamilyMember[] = [
    {
      id: 'fam-myself',
      patientId: 'pat-mison',
      name: 'Mison Khatiwada',
      relation: 'Myself',
      age: 26,
      gender: 'Male',
      bloodGroup: 'O+',
      allergies: ['Penicillin', 'Sulfonamides'],
      criticalConditions: ['Mild Essential Hypertension'],
      healthIdCode: 'AL-NP-8F29K4',
    },
    {
      id: 'fam-father',
      patientId: 'pat-mison',
      name: 'Ramesh Khatiwada',
      relation: 'Father',
      age: 58,
      gender: 'Male',
      bloodGroup: 'O+',
      allergies: ['None Known'],
      criticalConditions: ['Hypertension'],
      healthIdCode: 'AL-NP-8F29F1',
    },
    {
      id: 'fam-mother',
      patientId: 'pat-mison',
      name: 'Sita Devi Khatiwada',
      relation: 'Mother',
      age: 53,
      gender: 'Female',
      bloodGroup: 'B+',
      allergies: ['Dust'],
      criticalConditions: ['Osteoarthritis'],
      healthIdCode: 'AL-NP-8F29M2',
    },
    {
      id: 'fam-brother',
      patientId: 'pat-mison',
      name: 'Aarav Khatiwada',
      relation: 'Brother',
      age: 21,
      gender: 'Male',
      bloodGroup: 'O+',
      allergies: [],
      criticalConditions: [],
      healthIdCode: 'AL-NP-8F29B3',
    },
    {
      id: 'fam-child',
      patientId: 'pat-mison',
      name: 'Arya Khatiwada',
      relation: 'Child',
      age: 4,
      gender: 'Female',
      bloodGroup: 'O+',
      allergies: [],
      criticalConditions: [],
      healthIdCode: 'AL-NP-8F29C4',
    },
  ];

  const hospitals: Hospital[] = [
    {
      id: 'hosp-city',
      name: 'City Hospital',
      nameNe: 'सिटी अस्पताल',
      city: 'Bharatpur',
      district: 'Chitwan',
      address: 'Hospital Road-10, Bypass Chowk, Bharatpur, Chitwan',
      contact: '+977-056-524100',
      emergencyPhone: '102 / +977-056-524199',
      distanceKm: 2.1,
      rating: 4.7,
      reviewsCount: 418,
      hasEmergency: true,
      hasLab: true,
      hasPharmacy: true,
      hasInsurance: true,
      hasTelemedicine: true,
      openToday: true,
      verified: true,
      departments: ['dept-cardio', 'dept-genmed', 'dept-derm', 'dept-peds', 'dept-ortho', 'dept-ent', 'dept-gyn', 'dept-emerg'],
      coordinates: { lat: 27.6833, lng: 84.4333 },
    },
    {
      id: 'hosp-bmc',
      name: 'Bharatpur Medical Center',
      nameNe: 'भरतपुर मेडिकल सेन्टर',
      city: 'Bharatpur',
      district: 'Chitwan',
      address: 'Chaubiskothi, Bharatpur-10, Chitwan',
      contact: '+977-056-527800',
      emergencyPhone: '+977-056-527899',
      distanceKm: 3.8,
      rating: 4.6,
      reviewsCount: 312,
      hasEmergency: true,
      hasLab: true,
      hasPharmacy: true,
      hasInsurance: true,
      hasTelemedicine: false,
      openToday: true,
      verified: true,
      departments: ['dept-genmed', 'dept-peds', 'dept-ortho', 'dept-gyn', 'dept-emerg'],
      coordinates: { lat: 27.6789, lng: 84.4385 },
    },
    {
      id: 'hosp-chc',
      name: 'Chitwan Health Care',
      nameNe: 'चितवन हेल्थ केयर',
      city: 'Narayangarh',
      district: 'Chitwan',
      address: 'Lions Chowk, Narayangarh, Chitwan',
      contact: '+977-056-531400',
      emergencyPhone: '+977-056-531499',
      distanceKm: 5.2,
      rating: 4.5,
      reviewsCount: 195,
      hasEmergency: false,
      hasLab: true,
      hasPharmacy: true,
      hasInsurance: false,
      hasTelemedicine: true,
      openToday: true,
      verified: true,
      departments: ['dept-cardio', 'dept-derm', 'dept-ent', 'dept-genmed'],
      coordinates: { lat: 27.6981, lng: 84.4224 },
    },
  ];

  const departments: Department[] = [
    {
      id: 'dept-cardio',
      name: 'Cardiology',
      nameNe: 'मुटु रोग विभाग (Cardiology)',
      code: 'CARD',
      description: 'Heart rhythm, hypertension, coronary care, echocardiography, and preventive cardiology.',
      hospitalIds: ['hosp-city', 'hosp-chc'],
      iconName: 'HeartPulse',
    },
    {
      id: 'dept-genmed',
      name: 'General Medicine',
      nameNe: 'जनरल मेडिसिन (General Medicine)',
      code: 'GMED',
      description: 'Internal medicine, fever, diabetes, thyroid disorders, and systemic consultations.',
      hospitalIds: ['hosp-city', 'hosp-bmc', 'hosp-chc'],
      iconName: 'Stethoscope',
    },
    {
      id: 'dept-derm',
      name: 'Dermatology',
      nameNe: 'छाला तथा यौन रोग (Dermatology)',
      code: 'DERM',
      description: 'Clinical dermatology, allergies, eczema, and skin care procedures.',
      hospitalIds: ['hosp-city', 'hosp-chc'],
      iconName: 'Sparkles',
    },
    {
      id: 'dept-peds',
      name: 'Pediatrics',
      nameNe: 'बाल रोग विभाग (Pediatrics)',
      code: 'PEDS',
      description: 'Newborn care, child immunization, growth monitoring, and pediatric illnesses.',
      hospitalIds: ['hosp-city', 'hosp-bmc'],
      iconName: 'Baby',
    },
    {
      id: 'dept-ortho',
      name: 'Orthopedics',
      nameNe: 'हाडजोर्नी तथा नशा रोग (Orthopedics)',
      code: 'ORTH',
      description: 'Fracture care, joint replacement, spine disorders, and sports injury rehabilitation.',
      hospitalIds: ['hosp-city', 'hosp-bmc'],
      iconName: 'Bone',
    },
    {
      id: 'dept-ent',
      name: 'ENT',
      nameNe: 'नाक, कान, घाँटी (ENT)',
      code: 'ENT',
      description: 'Ear, nose, throat, sinus endoscopy, audiometry, and vertigo care.',
      hospitalIds: ['hosp-city', 'hosp-chc'],
      iconName: 'Ear',
    },
    {
      id: 'dept-gyn',
      name: 'Gynecology',
      nameNe: 'प्रसूति तथा स्त्री रोग (Gynecology)',
      code: 'GYN',
      description: 'Maternal health, antenatal care, high-risk pregnancy, and women wellness.',
      hospitalIds: ['hosp-city', 'hosp-bmc'],
      iconName: 'Activity',
    },
    {
      id: 'dept-emerg',
      name: 'Emergency',
      nameNe: 'आकस्मिक सेवा २४/७ (Emergency)',
      code: 'EMER',
      description: '24/7 acute trauma, cardiac life support, and rapid triage services.',
      hospitalIds: ['hosp-city', 'hosp-bmc'],
      iconName: 'Ambulance',
    },
  ];

  const doctors: Doctor[] = [
    {
      id: 'doc-suman',
      userId: 'usr-doc-suman',
      name: 'Dr. Suman Sharma',
      nameNe: 'डा. सुमन शर्मा',
      qualifications: 'MBBS, MD (Cardiology)',
      specialty: 'Cardiologist',
      specialtyNe: 'वरिष्ठ मुटु रोग विशेषज्ञ',
      departmentId: 'dept-cardio',
      departmentName: 'Cardiology',
      hospitalId: 'hosp-city',
      hospitalName: 'City Hospital',
      experienceYears: 12,
      rating: 4.8,
      reviewsCount: 246,
      consultationFee: 800,
      roomNumber: 'Room 4',
      availableToday: true,
      availableTomorrow: true,
      telemedicineAvailable: true,
      emergencyAvailable: true,
      onLeave: false,
      verified: true,
      nmcDemoBadge: 'DEMO-NMC-10482 (Fictional)',
      nextAvailableText: 'Today · 3:30 PM',
      utilizationRate: 82,
      schedule: [
        { day: 'Monday', startTime: '10:00 AM', endTime: '2:00 PM', isAvailable: true },
        { day: 'Wednesday', startTime: '4:00 PM', endTime: '7:00 PM', isAvailable: true },
        { day: 'Friday', startTime: '10:00 AM', endTime: '1:00 PM', isAvailable: true },
      ],
    },
    {
      id: 'doc-anita',
      userId: 'usr-doc-anita',
      name: 'Dr. Anita Karki',
      nameNe: 'डा. अनिता कार्की',
      qualifications: 'MBBS, MD (Internal Medicine)',
      specialty: 'General Physician',
      specialtyNe: 'फिजिसियन विशेषज्ञ',
      departmentId: 'dept-genmed',
      departmentName: 'General Medicine',
      hospitalId: 'hosp-city',
      hospitalName: 'City Hospital',
      experienceYears: 9,
      rating: 4.7,
      reviewsCount: 184,
      consultationFee: 650,
      roomNumber: 'Room 2',
      availableToday: true,
      availableTomorrow: true,
      telemedicineAvailable: true,
      emergencyAvailable: false,
      onLeave: false,
      verified: true,
      nmcDemoBadge: 'DEMO-NMC-12910 (Fictional)',
      nextAvailableText: 'Today · 4:00 PM',
      utilizationRate: 74,
      schedule: [
        { day: 'Sunday', startTime: '9:30 AM', endTime: '1:30 PM', isAvailable: true },
        { day: 'Tuesday', startTime: '2:00 PM', endTime: '5:30 PM', isAvailable: true },
        { day: 'Thursday', startTime: '10:00 AM', endTime: '2:00 PM', isAvailable: true },
      ],
    },
    {
      id: 'doc-raj',
      userId: 'usr-doc-raj',
      name: 'Dr. Raj Thapa',
      nameNe: 'डा. राज थापा',
      qualifications: 'MBBS, MS (Otorhinolaryngology)',
      specialty: 'ENT Specialist',
      specialtyNe: 'नाक, कान, घाँटी विशेषज्ञ',
      departmentId: 'dept-ent',
      departmentName: 'ENT',
      hospitalId: 'hosp-city',
      hospitalName: 'City Hospital',
      experienceYears: 10,
      rating: 4.6,
      reviewsCount: 152,
      consultationFee: 700,
      roomNumber: 'Room 7',
      availableToday: true,
      availableTomorrow: true,
      telemedicineAvailable: false,
      emergencyAvailable: true,
      onLeave: false,
      verified: true,
      nmcDemoBadge: 'DEMO-NMC-14205 (Fictional)',
      nextAvailableText: 'Today · 4:15 PM',
      utilizationRate: 69,
      schedule: [
        { day: 'Monday', startTime: '11:00 AM', endTime: '3:00 PM', isAvailable: true },
        { day: 'Wednesday', startTime: '11:00 AM', endTime: '3:00 PM', isAvailable: true },
        { day: 'Friday', startTime: '2:00 PM', endTime: '6:00 PM', isAvailable: true },
      ],
    },
  ];

  const slots: AppointmentSlot[] = [
    {
      id: 'slot-suman-245',
      doctorId: 'doc-suman',
      hospitalId: 'hosp-city',
      date: '2026-10-01',
      time: '2:45 PM',
      status: 'CONFIRMED',
      appointmentId: 'apt-a20',
    },
    {
      id: 'slot-suman-300',
      doctorId: 'doc-suman',
      hospitalId: 'hosp-city',
      date: '2026-10-01',
      time: '3:00 PM',
      status: 'CONFIRMED',
      appointmentId: 'apt-a21',
    },
    {
      id: 'slot-suman-330',
      doctorId: 'doc-suman',
      hospitalId: 'hosp-city',
      date: '2026-10-01',
      time: '3:30 PM',
      status: 'AVAILABLE',
    },
    {
      id: 'slot-suman-400',
      doctorId: 'doc-suman',
      hospitalId: 'hosp-city',
      date: '2026-10-01',
      time: '4:00 PM',
      status: 'AVAILABLE',
    },
    {
      id: 'slot-suman-430',
      doctorId: 'doc-suman',
      hospitalId: 'hosp-city',
      date: '2026-10-01',
      time: '4:30 PM',
      status: 'AVAILABLE',
    },
    {
      id: 'slot-suman-500',
      doctorId: 'doc-suman',
      hospitalId: 'hosp-city',
      date: '2026-10-01',
      time: '5:00 PM',
      status: 'BLOCKED',
    },
    {
      id: 'slot-anita-315',
      doctorId: 'doc-anita',
      hospitalId: 'hosp-city',
      date: '2026-10-01',
      time: '3:15 PM',
      status: 'CONFIRMED',
      appointmentId: 'apt-a22',
    },
    {
      id: 'slot-anita-400',
      doctorId: 'doc-anita',
      hospitalId: 'hosp-city',
      date: '2026-10-01',
      time: '4:00 PM',
      status: 'AVAILABLE',
    },
    {
      id: 'slot-anita-430',
      doctorId: 'doc-anita',
      hospitalId: 'hosp-city',
      date: '2026-10-01',
      time: '4:30 PM',
      status: 'AVAILABLE',
    },
    {
      id: 'slot-raj-320',
      doctorId: 'doc-raj',
      hospitalId: 'hosp-city',
      date: '2026-10-01',
      time: '3:20 PM',
      status: 'CONFIRMED',
      appointmentId: 'apt-a23',
    },
    {
      id: 'slot-raj-415',
      doctorId: 'doc-raj',
      hospitalId: 'hosp-city',
      date: '2026-10-01',
      time: '4:15 PM',
      status: 'AVAILABLE',
    },
  ];

  const appointments: Appointment[] = [
    {
      id: 'apt-a20',
      bookingId: 'AL-BK-20261001-0020',
      patientId: 'pat-dipak',
      patientName: 'Dipak Adhikari',
      forFamilyMemberId: 'fam-dipak',
      forRelation: 'Myself',
      hospitalId: 'hosp-city',
      hospitalName: 'City Hospital',
      hospitalAddress: 'Hospital Road-10, Bharatpur, Chitwan',
      hospitalContact: '+977-056-524100',
      departmentId: 'dept-cardio',
      departmentName: 'Cardiology',
      doctorId: 'doc-suman',
      doctorName: 'Dr. Suman Sharma',
      roomNumber: 'Room 4',
      slotId: 'slot-suman-245',
      date: '2026-10-01',
      displayDate: 'October 1, 2026',
      time: '2:45 PM',
      arriveBy: '2:30 PM',
      token: 'A-20',
      tokenNumber: 20,
      consultationFee: 800,
      type: 'IN_PERSON',
      paymentStatus: 'VERIFIED',
      paymentId: 'pay-0020',
      status: 'IN_CONSULTATION',
      qrCheckInToken: 'AL-QR-CHK-20261001-A20',
      checkedInAt: '2026-10-01T14:25:00Z',
      calledAt: '2026-10-01T14:46:00Z',
      instructions: 'Bring previous ECG and lipid profile reports. Arrive 15 minutes before appointment time.',
      createdAt: '2026-10-01T08:10:00Z',
    },
    {
      id: 'apt-a21',
      bookingId: 'AL-BK-20261001-0021',
      patientId: 'pat-ram',
      patientName: 'Ram Thapa',
      forFamilyMemberId: 'fam-ram',
      forRelation: 'Myself',
      hospitalId: 'hosp-city',
      hospitalName: 'City Hospital',
      hospitalAddress: 'Hospital Road-10, Bharatpur, Chitwan',
      hospitalContact: '+977-056-524100',
      departmentId: 'dept-cardio',
      departmentName: 'Cardiology',
      doctorId: 'doc-suman',
      doctorName: 'Dr. Suman Sharma',
      roomNumber: 'Room 4',
      slotId: 'slot-suman-300',
      date: '2026-10-01',
      displayDate: 'October 1, 2026',
      time: '3:00 PM',
      arriveBy: '2:45 PM',
      token: 'A-21',
      tokenNumber: 21,
      consultationFee: 800,
      type: 'IN_PERSON',
      paymentStatus: 'VERIFIED',
      paymentId: 'pay-0021',
      status: 'CHECKED_IN',
      qrCheckInToken: 'AL-QR-CHK-20261001-A21',
      checkedInAt: '2026-10-01T14:42:00Z',
      instructions: 'Routine post-angioplasty review. Fasting blood sugar sample already collected.',
      createdAt: '2026-10-01T08:30:00Z',
    },
    {
      id: 'apt-a22',
      bookingId: 'AL-BK-20261001-0022',
      patientId: 'pat-sita',
      patientName: 'Sita Karki',
      forFamilyMemberId: 'fam-sita',
      forRelation: 'Myself',
      hospitalId: 'hosp-city',
      hospitalName: 'City Hospital',
      hospitalAddress: 'Hospital Road-10, Bharatpur, Chitwan',
      hospitalContact: '+977-056-524100',
      departmentId: 'dept-genmed',
      departmentName: 'General Medicine',
      doctorId: 'doc-anita',
      doctorName: 'Dr. Anita Karki',
      roomNumber: 'Room 2',
      slotId: 'slot-anita-315',
      date: '2026-10-01',
      displayDate: 'October 1, 2026',
      time: '3:15 PM',
      arriveBy: '3:00 PM',
      token: 'A-22',
      tokenNumber: 22,
      consultationFee: 650,
      type: 'IN_PERSON',
      paymentStatus: 'VERIFIED',
      paymentId: 'pay-0022',
      status: 'WAITING',
      qrCheckInToken: 'AL-QR-CHK-20261001-A22',
      checkedInAt: '2026-10-01T14:55:00Z',
      instructions: 'Bring thyroid function test (TFT) report.',
      createdAt: '2026-10-01T09:05:00Z',
    },
    {
      id: 'apt-a23',
      bookingId: 'AL-BK-20261001-0023',
      patientId: 'pat-hari',
      patientName: 'Hari Gurung',
      forFamilyMemberId: 'fam-hari',
      forRelation: 'Myself',
      hospitalId: 'hosp-city',
      hospitalName: 'City Hospital',
      hospitalAddress: 'Hospital Road-10, Bharatpur, Chitwan',
      hospitalContact: '+977-056-524100',
      departmentId: 'dept-ent',
      departmentName: 'ENT',
      doctorId: 'doc-raj',
      doctorName: 'Dr. Raj Thapa',
      roomNumber: 'Room 7',
      slotId: 'slot-raj-320',
      date: '2026-10-01',
      displayDate: 'October 1, 2026',
      time: '3:20 PM',
      arriveBy: '3:05 PM',
      token: 'A-23',
      tokenNumber: 23,
      consultationFee: 700,
      type: 'IN_PERSON',
      paymentStatus: 'VERIFIED',
      paymentId: 'pay-0023',
      status: 'WAITING',
      qrCheckInToken: 'AL-QR-CHK-20261001-A23',
      checkedInAt: '2026-10-01T15:00:00Z',
      instructions: 'Avoid nasal decongestants 4 hours before examination.',
      createdAt: '2026-10-01T09:20:00Z',
    },
  ];

  const queues: QueueState[] = [
    {
      hospitalId: 'hosp-city',
      departmentId: 'dept-cardio',
      doctorId: 'doc-suman',
      doctorName: 'Dr. Suman Sharma',
      roomNumber: '4',
      currentToken: 'A-20',
      currentTokenNumber: 20,
      avgMinutesPerPatient: 6,
      updatedAt: '2026-10-01T14:50:00Z',
    },
  ];

  const payments: PaymentRecord[] = [
    {
      id: 'pay-0021',
      transactionUuid: 'AL-TXN-20261001-A21',
      appointmentId: 'apt-a21',
      patientId: 'pat-ram',
      patientName: 'Ram Thapa',
      hospitalId: 'hosp-city',
      amount: 800,
      taxAmount: 0,
      totalAmount: 800,
      productCode: 'EPAYTEST',
      gateway: 'ESEWA_UAT',
      signature: 'verified-hmac-sha256-a21',
      status: 'VERIFIED',
      esewaRefId: '00084912A',
      verifiedAt: '2026-10-01T08:31:00Z',
      createdAt: '2026-10-01T08:30:00Z',
    },
    {
      id: 'pay-0022',
      transactionUuid: 'AL-TXN-20261001-A22',
      appointmentId: 'apt-a22',
      patientId: 'pat-sita',
      patientName: 'Sita Karki',
      hospitalId: 'hosp-city',
      amount: 650,
      taxAmount: 0,
      totalAmount: 650,
      productCode: 'EPAYTEST',
      gateway: 'ESEWA_UAT',
      signature: 'verified-hmac-sha256-a22',
      status: 'VERIFIED',
      esewaRefId: '00084915B',
      verifiedAt: '2026-10-01T09:06:00Z',
      createdAt: '2026-10-01T09:05:00Z',
    },
    {
      id: 'pay-0023',
      transactionUuid: 'AL-TXN-20261001-A23',
      appointmentId: 'apt-a23',
      patientId: 'pat-hari',
      patientName: 'Hari Gurung',
      hospitalId: 'hosp-city',
      amount: 700,
      taxAmount: 0,
      totalAmount: 700,
      productCode: 'EPAYTEST',
      gateway: 'ESEWA_UAT',
      signature: 'verified-hmac-sha256-a23',
      status: 'VERIFIED',
      esewaRefId: '00084919C',
      verifiedAt: '2026-10-01T09:21:00Z',
      createdAt: '2026-10-01T09:20:00Z',
    },
  ];

  const prescriptions: Prescription[] = [
    {
      id: 'rx-prev-01',
      rxCode: 'RX-27910',
      appointmentId: 'apt-prev-01',
      patientId: 'pat-mison',
      patientName: 'Mison Khatiwada',
      forRelation: 'Myself',
      doctorId: 'doc-suman',
      doctorName: 'Dr. Suman Sharma',
      hospitalId: 'hosp-city',
      hospitalName: 'City Hospital',
      departmentName: 'Cardiology',
      diagnosis: 'Stage 1 Essential Hypertension — Stable',
      symptoms: 'Occasional mild occipital headache after long screen hours.',
      clinicalNotes: 'BP 132/84 mmHg, HR 74 bpm regular, Heart sounds S1 S2 normal, no murmur.',
      medicines: [
        {
          name: 'Amlodipine',
          strength: '5mg',
          dosage: '1 tablet',
          frequency: '1 time/day (Morning)',
          duration: '30 days',
          instructions: 'Take after breakfast with water.',
        },
      ],
      followUpDate: 'October 1, 2026',
      createdAt: '2026-09-18T10:30:00Z',
      displayDate: 'SEP 18, 2026',
      displayTime: '10:30 AM',
    },
  ];

  const pharmacyOrders: PharmacyOrder[] = [
    {
      id: 'pho-01',
      orderCode: 'PH-9021',
      prescriptionId: 'rx-prev-01',
      rxCode: 'RX-27910',
      patientId: 'pat-mison',
      patientName: 'Mison Khatiwada',
      hospitalId: 'hosp-city',
      pharmacyName: 'City Hospital Central Dispensary',
      medicinesCount: 1,
      medicines: prescriptions[0].medicines,
      totalAmount: 210,
      status: 'Delivered',
      updatedAt: '2026-09-18T11:00:00Z',
      createdAt: '2026-09-18T10:35:00Z',
    },
  ];

  const labCatalog: LabTestCatalog[] = [
    {
      id: 'test-cbc',
      code: 'CBC-01',
      name: 'Complete Blood Count (CBC)',
      category: 'Hematology',
      price: 350,
      turnaroundHours: 2,
      availableToday: true,
      preparation: 'No fasting required. EDTA whole blood sample.',
    },
    {
      id: 'test-lipid',
      code: 'LIP-02',
      name: 'Lipid Profile (Cholesterol, Triglycerides, HDL, LDL)',
      category: 'Biochemistry',
      price: 850,
      turnaroundHours: 4,
      availableToday: true,
      preparation: '10–12 hours overnight fasting required.',
    },
    {
      id: 'test-fbs',
      code: 'GLU-01',
      name: 'Blood Sugar (Fasting / PP)',
      category: 'Biochemistry',
      price: 200,
      turnaroundHours: 1,
      availableToday: true,
      preparation: '8 hours fasting for FBS.',
    },
    {
      id: 'test-tft',
      code: 'TFT-03',
      name: 'Thyroid Function Test (TSH, Free T3, Free T4)',
      category: 'Endocrinology',
      price: 1100,
      turnaroundHours: 6,
      availableToday: true,
      preparation: 'Morning sample preferred.',
    },
    {
      id: 'test-troponin',
      code: 'CRD-09',
      name: 'High-Sensitivity Troponin-I & ECG Panel',
      category: 'Cardiac Markers',
      price: 1450,
      turnaroundHours: 1,
      availableToday: true,
      preparation: 'Stat cardiac workup — no preparation needed.',
    },
  ];

  const labOrders: LabOrder[] = [
    {
      id: 'lab-prev-sep18',
      orderCode: 'LAB-20260918-01',
      patientId: 'pat-mison',
      patientName: 'Mison Khatiwada',
      forRelation: 'Myself',
      hospitalId: 'hosp-city',
      hospitalName: 'City Hospital',
      orderedByDoctorId: 'doc-suman',
      orderedByDoctorName: 'Dr. Suman Sharma',
      testId: 'test-cbc',
      testName: 'CBC',
      price: 350,
      scheduledDate: 'SEP 18, 2026',
      scheduledTime: '11:00 AM',
      status: 'Report Ready',
      paymentStatus: 'VERIFIED',
      reportSummary: 'Hemoglobin, total leukocyte count, differential count, and platelets are within normal physiological reference intervals.',
      reportParameters: [
        { parameter: 'Hemoglobin (Hb)', value: '14.8', unit: 'g/dL', referenceRange: '13.5 – 17.5', flag: 'Normal' },
        { parameter: 'Total WBC Count', value: '6,800', unit: '/cumm', referenceRange: '4,000 – 11,000', flag: 'Normal' },
        { parameter: 'Platelet Count', value: '245,000', unit: '/cumm', referenceRange: '150,000 – 450,000', flag: 'Normal' },
        { parameter: 'Hematocrit (PCV)', value: '43.5', unit: '%', referenceRange: '40.0 – 50.0', flag: 'Normal' },
      ],
      reportUploadedAt: '2026-09-18T13:15:00Z',
      reportUploadedBy: 'Dipesh Shrestha (Pathology Lab)',
      createdAt: '2026-09-18T10:40:00Z',
    },
    {
      id: 'lab-ram-today',
      orderCode: 'LAB-20261001-02',
      patientId: 'pat-ram',
      patientName: 'Ram Thapa',
      forRelation: 'Myself',
      hospitalId: 'hosp-city',
      hospitalName: 'City Hospital',
      orderedByDoctorId: 'doc-suman',
      orderedByDoctorName: 'Dr. Suman Sharma',
      testId: 'test-fbs',
      testName: 'Blood Sugar',
      price: 200,
      scheduledDate: 'OCT 1, 2026',
      scheduledTime: '11:00 AM',
      status: 'Sample Collected',
      paymentStatus: 'VERIFIED',
      createdAt: '2026-10-01T10:15:00Z',
    },
  ];

  const timeline: TimelineEvent[] = [
    {
      id: 'tl-sep18-cbc',
      patientId: 'pat-mison',
      dateGroup: 'SEP 18, 2026',
      time: '1:15 PM',
      title: 'CBC Report',
      subtitle: 'City Hospital Central Laboratory · All parameters normal (Hb 14.8 g/dL)',
      category: 'LAB_REPORT',
      completed: true,
      referenceId: 'lab-prev-sep18',
      timestamp: 1758201300000,
    },
    {
      id: 'tl-sep18-rx',
      patientId: 'pat-mison',
      dateGroup: 'SEP 18, 2026',
      time: '10:30 AM',
      title: 'Baseline Cardiology Consultation & Prescription',
      subtitle: 'Dr. Suman Sharma · City Hospital (RX-27910)',
      category: 'PRESCRIPTION',
      completed: true,
      referenceId: 'rx-prev-01',
      timestamp: 1758191400000,
    },
  ];

  const insuranceClaims: InsuranceClaim[] = [
    {
      id: 'clm-01',
      claimCode: 'HIB-CLM-2026-991',
      patientId: 'pat-ram',
      patientName: 'Ram Thapa',
      policyNumber: 'HIB-NP-2026-44109',
      providerName: 'Nepal Health Insurance Board (HIB)',
      hospitalId: 'hosp-city',
      hospitalName: 'City Hospital',
      appointmentId: 'apt-a21',
      diagnosis: 'Ischemic Heart Disease Follow-Up & Glycemic Panel',
      claimAmount: 1800,
      approvedAmount: 1800,
      status: 'Approved',
      submittedAt: '2026-10-01T09:00:00Z',
    },
    {
      id: 'clm-02',
      claimCode: 'HIB-CLM-2026-994',
      patientId: 'pat-mison',
      patientName: 'Mison Khatiwada',
      policyNumber: 'HIB-NP-2026-88412',
      providerName: 'Nepal Health Insurance Board (HIB)',
      hospitalId: 'hosp-city',
      hospitalName: 'City Hospital',
      diagnosis: 'Essential Hypertension Outpatient Diagnostics',
      claimAmount: 1150,
      status: 'Under Review',
      submittedAt: '2026-09-18T14:00:00Z',
    },
  ];

  const telemedicineSessions: TelemedicineSession[] = [
    {
      id: 'tele-01',
      appointmentId: 'apt-a24',
      roomCode: 'AYU-TELE-CARDIO-404',
      patientId: 'pat-mison',
      patientName: 'Mison Khatiwada',
      doctorId: 'doc-suman',
      doctorName: 'Dr. Suman Sharma',
      status: 'Scheduled',
    },
  ];

  const notifications: AppNotification[] = [
    {
      id: 'notif-init-1',
      recipientRole: 'patient',
      recipientUserId: 'usr-patient-mison',
      type: 'Appointment Reminder',
      title: 'Welcome to AyuLink Nepal',
      message: 'Your One Health ID (AL-NP-8F29K4) is active across City Hospital, Bharatpur Medical Center, and Chitwan Health Care.',
      read: false,
      createdAt: '2026-10-01T08:00:00Z',
      displayTime: '8:00 AM',
    },
  ];

  const auditLogs: AuditLogEntry[] = [
    {
      id: 'aud-01',
      actorId: 'usr-hosp-admin',
      actorName: 'Prakash Adhikari',
      actorRole: 'hospital_admin',
      action: 'Hospital viewed appointment roster',
      targetType: 'Appointment',
      targetId: 'apt-a21',
      hospitalId: 'hosp-city',
      ipAddress: '202.45.144.18',
      details: 'Accessed October 1 Cardiology outpatient schedule and verified eSewa UAT settlement.',
      timestamp: '2026-10-01 08:35:12 NPT',
    },
    {
      id: 'aud-02',
      actorId: 'usr-doc-suman',
      actorName: 'Dr. Suman Sharma',
      actorRole: 'doctor',
      action: 'Doctor viewed patient record',
      targetType: 'PatientRecord',
      targetId: 'pat-ram',
      hospitalId: 'hosp-city',
      ipAddress: '202.45.144.22',
      details: 'Authorized clinical access to Ram Thapa medical history for Token A-21.',
      timestamp: '2026-10-01 09:12:44 NPT',
    },
    {
      id: 'aud-03',
      actorId: 'usr-super-admin',
      actorName: 'AyuLink National Governance',
      actorRole: 'super_admin',
      action: 'Admin changed doctor verification',
      targetType: 'DoctorVerification',
      targetId: 'doc-suman',
      hospitalId: 'hosp-city',
      ipAddress: '110.44.120.9',
      details: 'Verified fictional demo credential DEMO-NMC-10482 for Cardiology department.',
      timestamp: '2026-09-30 17:40:00 NPT',
    },
  ];

  return {
    users,
    patientProfiles,
    familyMembers,
    hospitals,
    departments,
    doctors,
    slots,
    appointments,
    queues,
    payments,
    prescriptions,
    pharmacyOrders,
    labCatalog,
    labOrders,
    timeline,
    insuranceClaims,
    telemedicineSessions,
    notifications,
    auditLogs,
    tokenCounter: 23,
  };
}
